version: "3"

services:
  backend:
    build: ../pokeback
    env_file:
      - ../pokeback/.env.development
    ports:
      - "8080:8080"
    tty: true
  frontend:
    build: ../pokefront
    env_file:
      - ../pokefront/.env.development
    ports:
      - "3000:3000"
    tty: true
  strapi:
    container_name: strapi
    build: ../zrp-pokemon
    restart: unless-stopped
    env_file: ../zrp-pokemon/.env.example
    ports:
      - "1337:1337"
